language: python
python:
  - "2.7"

# django versions to test
env:
# - DJANGO_VERSION=1.5
# - DJANGO_VERSION=1.6
- DJANGO_VERSION=1.7

# command to install dependencies
install:
    - pip install -q Django==$DJANGO_VERSION

# command to run tests
script: make test

# notifications after testing
notifications:
  email:
    recipients:
    - benjamin@bengfort.com
    on_success: change
    on_failure: always
