language: python
python:
  - "2.7"
  - "3.5"

# django versions to test
env:
- DJANGO_VERSION=1.5
- DJANGO_VERSION=1.6
- DJANGO_VERSION=1.7
- DJANGO_VERSION=1.8
- DJANGO_VERSION=1.9

# command to install dependencies
install:
    - pip install -q Django==$DJANGO_VERSION

# command to run tests
script: make test

# notifications after testing
notifications:
  email:
    recipients:
    - benjamin@bengfort.com
    on_success: change
    on_failure: always
